language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"
  - "nightly"

services:
  - mysql
  - postgresql
  - mongodb
addons:
  postgresql: "10"

env:
  matrix:
    - DJANGO=1.11
    - DJANGO=2.2
    - DJANGO=3.0
    - DJANGO=master

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-django${DJANGO}
  - pip install virtualenv tox
  - tox -e $TOX_ENV --notest

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e $TOX_ENV -- pip install coveralls
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION

matrix:
  fast_finish: true
  include:
    - python: "3.7"
      env: TOX_ENV=lint
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: "3.7"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: "3.7"
      env: ENV=functional
      install:
        - pip install tox
        - export PYTHON='coverage run -a'
      before_install:
        - mysql -e 'CREATE DATABASE test;'
        - psql -c 'CREATE DATABASE test;' -U postgres
      script:
        - DATABASE_URL=sqlite:////tmp/db.sqlite tox -e functional
        - DATABASE_URL=mysql://travis:@localhost/test tox -e functional
        - DATABASE_URL=postgres://postgres:@localhost/test tox -e functional
        - CONNECTOR=dbbackup.db.postgresql.PgDumpBinaryConnector DATABASE_URL=postgres://postgres:@localhost/test tox -e functional
  exclude:
    - python: "nightly"
      env: DJANGO=1.11
    - python: "pypy"
      env: DJANGO=2.2
    - python: "pypy"
      env: DJANGO=3.0
    - python: "pypy"
      env: DJANGO=master
    - python: "2.7"
      env: DJANGO=2.2
    - python: "2.7"
      env: DJANGO=3.0
    - python: "2.7"
      env: DJANGO=master
    - python: "3.5"
      env: DJANGO=3.0
    - python: "3.5"
      env: DJANGO=master
  allow_failures:
    - python: "pypy3"
    - python: "nightly"
    - env: DJANGO=master
